"""Add entry_time and exit_time columns to Attendance

Revision ID: 8064f2733331
Revises: 8717beae9b04
Create Date: 2024-11-02 23:49:43.458275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8064f2733331'
down_revision = '8717beae9b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('entry_time', sa.DateTime(), nullable=True))
    op.add_column('attendances', sa.Column('exit_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendances', 'exit_time')
    op.drop_column('attendances', 'entry_time')
    # ### end Alembic commands ###
