"""Add event_type column to Attendance

Revision ID: 8717beae9b04
Revises: 3f4bbdfb285f
Create Date: 2024-11-02 23:37:38.003125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8717beae9b04'
down_revision = '3f4bbdfb285f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('event_type', sa.String(length=10), nullable=False, server_default='entry'))

    # Remove the default constraint if needed
    op.alter_column('attendances', 'event_type', server_default=None)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendances', 'event_type')
    # ### end Alembic commands ###
